# Generated by Django 6.1 on 2026-08-25 03:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Vehiculo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('placa', models.CharField(max_length=7, unique=True, verbose_name='Placa o Matrícula')),
                ('marca', models.CharField(max_length=50, verbose_name='Marca del Fabricante')),
                ('modelo', models.CharField(max_length=50, verbose_name='Línea o Modelo')),
                ('anio_fabricacion', models.IntegerField(verbose_name='Año de Fabricación')),
                ('kilometraje', models.DecimalField(decimal_places=2, default=0.0, max_digits=10, verbose_name='Kilometraje Acumulado (km)')),
                ('tarifa_diaria', models.DecimalField(decimal_places=2, max_digits=8, verbose_name='Tarifa de Alquiler por Día (USD)')),
                ('en_servicio', models.BooleanField(default=True, verbose_name='Disponible para Servicio')),
                ('ultimo_mantenimiento', models.DateTimeField(blank=True, null=True, verbose_name='Fecha y Hora de Último Mantenimiento')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Registro')),
            ],
            options={
                'verbose_name': 'Vehículo',
                'verbose_name_plural': 'Vehículos',
                'ordering': ['-created_at'],
            },
        ),
    ]
